"""
task.

Revision ID: f543ec1c63d1
Revises: cbe0f3e1e499
Create Date: 2025-03-30 19:46:33.089356

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f543ec1c63d1'
down_revision: str | None = 'cbe0f3e1e499'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'task',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('result', sa.TEXT(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_task')),
    )
    op.create_table(
        'file_metadata',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=True),
        sa.Column('content_type', sa.String(length=255), nullable=True),
        sa.Column('task_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_file_metadata_task_id_task')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_file_metadata')),
    )
    op.create_index(op.f('ix_file_metadata_task_id'), 'file_metadata', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_metadata_task_id'), table_name='file_metadata')
    op.drop_table('file_metadata')
    op.drop_table('task')
    # ### end Alembic commands ###
