"""
tokens.

Revision ID: cbe0f3e1e499
Revises:
Create Date: 2025-03-25 18:02:28.039573

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cbe0f3e1e499'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'service_token',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('service_name', sa.String(length=255), nullable=False),
        sa.Column('hashed_token', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_service_token')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_token')
    # ### end Alembic commands ###
