version: 1
disable_existing_loggers: False

formatters:
  json:
    class: tochka_infrastructure.logs.JsonFormatter
    format: '%(name)s %(module)s %(lineno)s %(pathname)s %(args)s %(msg)s %(funcName)s'

filters:
  readiness_filter:
    (): tochka_infrastructure.logs.filters.UvicornAccessLogFilter
    path: /readiness
  liveness_filter:
    (): tochka_infrastructure.logs.filters.UvicornAccessLogFilter
    path: /liveness

handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout

root:
  level: INFO
  handlers:
    - console

loggers:
  uvicorn.access:
    filters:
      - readiness_filter
      - liveness_filter
