version: 1
disable_existing_loggers: False

formatters:
  plain:
    class: logging.Formatter
    format: '[%(asctime)s][%(levelname)-8s][%(name)s][%(module)-10s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: plain

root:
  level: INFO
  handlers:
    - console
